### ISSUE TITLE
構造について

### ISSUE THREAD

**Issue by Huyu2239** [Seiwell0610/Arknights-BOT#18]
https://github.com/Seiwell0610/Arknights-BOT/blob/20537631db5c63fdfde8ad5303512cd3d014be71/cogs/global_chat.py
このファイルについてなんですが、ごちゃごちゃし始めたので
グローバルチャットの設定系のcogとそれ以外の処理という意味で
- on_globalchat.py
- setting_globalchat.py
のようにわけたら見やすいかと思います。

**Comment by Seiwell0610** [comment]
> https://github.com/Seiwell0610/Arknights-BOT/blob/20537631db5c63fdfde8ad5303512cd3d014be71/cogs/global_chat.py
> このファイルについてなんですが、ごちゃごちゃし始めたので
> グローバルチャットの設定系のcogとそれ以外の処理という意味で
> 
> * on_globalchat.py
> * setting_globalchat.py
>   のようにわけたら見やすいかと思います。

なるほど、その方が良さそうですね。
土日に変更作業を行えたらしたいと思います。

**Comment by Huyu2239** [comment]
いくつか改善点ありそうなので（時間があるときに）言っておきます

**Comment by Seiwell0610** [comment]
了解です。

**Comment by Huyu2239** [comment]
cogsディレクトリの中にいくつかフォルダを作り、os&forで読み込むほうが
変更時にえくすてんしょんlistの中身をいじらなくてもよくなると思います

**Comment by Seiwell0610** [comment]
動作確認しました。

**Comment by Huyu2239** [comment]
٩(｡•ω•｡*)وいぇい

**Comment by Seiwell0610** [comment]
Closeしてもよろし？
